# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###

POST http://127.0.0.1:8000/api/apages/
Content-Type: application/json
Accept: application/json
x-api-key: 2342034fhswefwefwer3424weerr

{
  "keyword": "B3",
  "unit": "Rulle"
}

###

POST https://alarm.t0n.eu/api/apages/
Content-Type: application/json
Accept: application/json
x-api-key: {{apikey}}

{
  "keyword": "B3",
  "unit": "Rulle"
}
